import {addObservationBatch,parseObservationCsv,queryObservations,type BatchResult,type ObservationRecord} from './observation-store'
import {variableByKey} from './variable-registry'

export type SensorStatus='ACTIVE'|'INACTIVE'|'MAINTENANCE'
export type SensorHealth='HEALTHY'|'WATCH'|'STALE'|'NO_DATA'|'CALIBRATION_DUE'
export type SensorCalibration={date:string;method:string;reference:string;nextDue?:string;coefficient?:number;offset?:number;note?:string}
export type FieldSensor={id:string;farmId:string;zoneId:string;name:string;variable:string;unit:string;manufacturer?:string;model?:string;serialNumber?:string;installationDate?:string;expectedIntervalMinutes:number;status:SensorStatus;calibration?:SensorCalibration;notes?:string;createdAt:string;updatedAt:string}
export type SensorHealthRecord={sensorId:string;health:SensorHealth;lastObservationAt?:string;ageMinutes?:number;latestQuality?:ObservationRecord['quality'];calibrationDue:boolean;messages:string[]}
const DB='cropsmart-field-sensor-db',VERSION=1,STORE='sensors'
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('farmId','farmId');s.createIndex('zoneId','zoneId');s.createIndex('variable','variable');s.createIndex('status','status')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(v:FieldSensor){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
async function all(){const db=await openDb();const rows=await new Promise<FieldSensor[]>((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result as FieldSensor[]);r.onerror=()=>reject(r.error)});db.close();return rows}
export async function saveFieldSensor(input:Omit<FieldSensor,'createdAt'|'updatedAt'>){const def=variableByKey[input.variable];if(!def)throw new Error('Sensor variable is not registered.');if(input.unit!==def.unit)throw new Error(`Sensor unit must match registry unit ${def.unit}.`);if(input.expectedIntervalMinutes<=0)throw new Error('Expected interval must be greater than zero.');const now=new Date().toISOString();const existing=(await all()).find(s=>s.id===input.id);const sensor:FieldSensor={...input,createdAt:existing?.createdAt??now,updatedAt:now};await put(sensor);return sensor}
export async function listFieldSensors(){return (await all()).sort((a,b)=>a.name.localeCompare(b.name))}
export async function getSensorHealth(sensor:FieldSensor):Promise<SensorHealthRecord>{const obs=await queryObservations({sensorId:sensor.id,sourceMode:'OBSERVED',limit:10});const latest=obs[0],messages:string[]=[];const calibrationDue=!!sensor.calibration?.nextDue&&Date.parse(sensor.calibration.nextDue)<=Date.now();if(calibrationDue)messages.push('Calibration due date has passed.');if(sensor.status!=='ACTIVE')messages.push(`Sensor status is ${sensor.status}.`);if(!latest)return{sensorId:sensor.id,health:calibrationDue?'CALIBRATION_DUE':'NO_DATA',calibrationDue,messages:[...messages,'No observed measurements found.']};const ageMinutes=(Date.now()-Date.parse(latest.timestamp))/60000;if(latest.quality==='FAIL'||latest.quality==='SUSPECT')messages.push(`Latest observation quality is ${latest.quality}.`);if(ageMinutes>sensor.expectedIntervalMinutes*3)messages.push(`Latest observation is older than three expected reporting intervals.`);let health:SensorHealth='HEALTHY';if(calibrationDue)health='CALIBRATION_DUE';else if(ageMinutes>sensor.expectedIntervalMinutes*3)health='STALE';else if(latest.quality!=='PASS')health='WATCH';return{sensorId:sensor.id,health,lastObservationAt:latest.timestamp,ageMinutes:+ageMinutes.toFixed(1),latestQuality:latest.quality,calibrationDue,messages}}
export async function sensorHealthSummary(){const sensors=await listFieldSensors();return Promise.all(sensors.map(getSensorHealth))}
export async function importFieldObservationCsv(text:string):Promise<{batch:BatchResult;unregisteredSensorIds:string[]}>{const parsed=parseObservationCsv(text);if(parsed.errors.length)throw new Error(parsed.errors.join(' '));const sensors=await listFieldSensors(),registered=new Set(sensors.map(s=>s.id)),unregistered=[...new Set(parsed.rows.map(r=>r.sensorId).filter(id=>!registered.has(id)))];const batch=await addObservationBatch(parsed.rows);return{batch,unregisteredSensorIds:unregistered}}
export function sensorRegistryJson(sensors:FieldSensor[],health:SensorHealthRecord[]){return JSON.stringify({schemaVersion:'1.0',generatedAt:new Date().toISOString(),sensors,health},null,2)}
