import {getScientificModel,type ScientificModel} from './scientific-model-registry'
export type DatasetRole='CALIBRATION'|'VALIDATION'
export type CalibrationDataset={id:string;name:string;modelId:string;role:DatasetRole;variable:string;unit:string;createdAt:string;sourceNote:string;observed:number[];modeled:number[]}
export type PerformanceMetrics={n:number;mae:number;rmse:number;bias:number;r2:number|null;nrmsePct:number|null}
export type ValidationRun={id:string;modelId:string;modelVersion:string;datasetId:string;datasetRole:DatasetRole;createdAt:string;metrics:PerformanceMetrics;criteria:PromotionCriteria;criteriaResults:Record<string,boolean>;eligibleForPromotion:boolean;decision:'ELIGIBLE_FOR_REVIEW'|'NOT_ELIGIBLE';limitations:string[]}
export type PromotionCriteria={minimumN:number;maximumNrmsePct:number;maximumAbsoluteBias:number;minimumR2:number}
const DB='cropsmart-model-validation-db',VERSION=1,DATASETS='datasets',RUNS='runs'
const DEFAULT:PromotionCriteria={minimumN:20,maximumNrmsePct:25,maximumAbsoluteBias:0.1,minimumR2:0.6}
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(DATASETS)){const s=db.createObjectStore(DATASETS,{keyPath:'id'});s.createIndex('modelId','modelId');s.createIndex('role','role')}if(!db.objectStoreNames.contains(RUNS)){const s=db.createObjectStore(RUNS,{keyPath:'id'});s.createIndex('modelId','modelId');s.createIndex('datasetId','datasetId')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(store:string,value:unknown){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
async function all<T>(store:string){const db=await openDb();const rows=await new Promise<T[]>((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result as T[]);r.onerror=()=>reject(r.error)});db.close();return rows}
export async function saveCalibrationDataset(input:Omit<CalibrationDataset,'id'|'createdAt'>){if(input.observed.length!==input.modeled.length||input.observed.length<2)throw new Error('Observed and modeled arrays must have equal length and at least two paired values.');if(!getScientificModel(input.modelId))throw new Error('Scientific Model Registry entry not found.');if([...input.observed,...input.modeled].some(v=>!Number.isFinite(v)))throw new Error('Dataset contains a non-finite numeric value.');const createdAt=new Date().toISOString(),d:CalibrationDataset={...input,id:`DATA-${input.role.slice(0,3)}-${Date.now().toString(36).toUpperCase()}`,createdAt};await put(DATASETS,d);return d}
export async function listCalibrationDatasets(){return (await all<CalibrationDataset>(DATASETS)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export async function listValidationRuns(){return (await all<ValidationRun>(RUNS)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export function calculatePerformanceMetrics(observed:number[],modeled:number[]):PerformanceMetrics{const n=observed.length,err=modeled.map((v,i)=>v-observed[i]),mae=err.reduce((s,e)=>s+Math.abs(e),0)/n,rmse=Math.sqrt(err.reduce((s,e)=>s+e*e,0)/n),bias=err.reduce((s,e)=>s+e,0)/n,mean=observed.reduce((s,v)=>s+v,0)/n,sst=observed.reduce((s,v)=>s+(v-mean)**2,0),sse=err.reduce((s,e)=>s+e*e,0),r2=sst>0?1-sse/sst:null,nrmsePct=Math.abs(mean)>1e-12?100*rmse/Math.abs(mean):null;return{n,mae,rmse,bias,r2,nrmsePct}}
export async function runValidation(datasetId:string,criteria:PromotionCriteria=DEFAULT){const datasets=await listCalibrationDatasets(),d=datasets.find(x=>x.id===datasetId);if(!d)throw new Error('Dataset not found.');const model=getScientificModel(d.modelId) as ScientificModel|undefined;if(!model)throw new Error('Model not found.');const metrics=calculatePerformanceMetrics(d.observed,d.modeled),criteriaResults={minimumN:metrics.n>=criteria.minimumN,maximumNrmsePct:metrics.nrmsePct!==null&&metrics.nrmsePct<=criteria.maximumNrmsePct,maximumAbsoluteBias:Math.abs(metrics.bias)<=criteria.maximumAbsoluteBias,minimumR2:metrics.r2!==null&&metrics.r2>=criteria.minimumR2},eligibleForPromotion=d.role==='VALIDATION'&&Object.values(criteriaResults).every(Boolean),createdAt=new Date().toISOString();const run:ValidationRun={id:`VAL-${Date.now().toString(36).toUpperCase()}`,modelId:model.id,modelVersion:model.version,datasetId:d.id,datasetRole:d.role,createdAt,metrics,criteria,criteriaResults,eligibleForPromotion,decision:eligibleForPromotion?'ELIGIBLE_FOR_REVIEW':'NOT_ELIGIBLE',limitations:['Passing numerical criteria does not automatically change Scientific Model Registry status.','Calibration and validation datasets must remain distinct for defensible out-of-sample evaluation.','Promotion requires documented scientific review of dataset provenance, representativeness, residual behavior and applicability boundaries.']};await put(RUNS,run);return run}
export function parsePairedCsv(text:string){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<3)throw new Error('CSV requires a header and at least two data rows.');const header=lines[0].split(',').map(x=>x.trim().toLowerCase()),oi=header.indexOf('observed'),mi=header.indexOf('modeled');if(oi<0||mi<0)throw new Error('CSV header must contain observed and modeled columns.');const observed:number[]=[],modeled:number[]=[];for(const line of lines.slice(1)){const c=line.split(',').map(x=>x.trim()),o=Number(c[oi]),m=Number(c[mi]);if(!Number.isFinite(o)||!Number.isFinite(m))throw new Error(`Invalid numeric pair: ${line}`);observed.push(o);modeled.push(m)}return{observed,modeled}}
export function validationRunJson(run:ValidationRun){return JSON.stringify(run,null,2)}
