import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { AV_MODELS, DEFAULT_SETTINGS, createIllustrativeParameters, simulateAV, compareAV } from '../src/lib/avModelLaboratory.ts'
const p=createIllustrativeParameters(),s={...DEFAULT_SETTINGS}
const near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-7,`${actual} != ${expected}`)
test('15 unique catalogue entries have local optimized assets',()=>{assert.equal(AV_MODELS.length,15);assert.equal(new Set(AV_MODELS.map(m=>m.id)).size,15);for(const m of AV_MODELS)assert.ok(existsSync(new URL(`../public${m.image}`,import.meta.url)))})
test('known irrigation and pump units; zero default savings',()=>{const r=simulateAV('SS01',p.SS01,s);near(r.irrigationM3,5000);near(r.pumpEnergyKwh,681.25);near(r.pvEnergyKwh,216000);near(r.waterSavedPct,0)})
test('configuration selection propagates density without assuming crop benefits',()=>{const rows=compareAV(['SS01','CS01'],p,s);assert.notEqual(rows[0].pvEnergyKwh,rows[1].pvEnergyKwh);assert.equal(rows[0].irrigationM3,rows[1].irrigationM3)})
test('water savings depend on explicit baseline, demand and application efficiency',()=>{near(simulateAV('SS01',{...p.SS01,netIrrigationRatio:.8},s).waterSavedPct,20);near(simulateAV('SS01',{...p.SS01,netIrrigationRatio:1.2},s).waterSavedPct,-20);near(simulateAV('SS01',{...p.SS01,irrigationEfficiency:1},s).waterSavedPct,20);assert.equal(simulateAV('SS01',p.SS01,{...s,baselineNetIrrigationMmYear:0}).waterSavedPct,null)})
test('equal capacity normalizes PV and scales land and irrigation',()=>{const rows=compareAV(['SS01','CS01'],p,{...s,mode:'equal-capacity'});near(rows[0].pvEnergyKwh,rows[1].pvEnergyKwh);assert.notEqual(rows[0].areaHa,rows[1].areaHa);near(rows[0].irrigationM3PerHa,rows[1].irrigationM3PerHa)})
test('equal land area scaling preserves per hectare outputs',()=>{const a=simulateAV('SS01',p.SS01,s),b=simulateAV('SS01',p.SS01,{...s,areaHa:2});near(b.pvEnergyKwh,2*a.pvEnergyKwh);near(b.irrigationM3,2*a.irrigationM3);near(b.pvKwhPerHa,a.pvKwhPerHa)})
test('zero-discount economics use annual horizon and incremental pumping',()=>{const r=simulateAV('SS01',{...p.SS01,pvKwPerHa:1,poaKwhPerM2Year:1000,performanceRatio:1,capexPerKw:1000,opexPerKwYear:20},{...s,discountRate:0,lifetimeYears:10,electricityValuePerKwh:.2});near(r.annualCashFlow,180);near(r.npv,800);near(r.annualizedNetBenefit,80);near(r.lcoe,.12);near(r.simplePaybackYears,1000/180)})
test('zero generation or no positive cash flow has no LCOE or payback',()=>{const r=simulateAV('SS01',{...p.SS01,performanceRatio:0},s);assert.equal(r.lcoe,null);assert.equal(r.simplePaybackYears,null)})
test('invalid and nonfinite engineering parameters are rejected',()=>{for(const patch of [{pvKwPerHa:0},{pvKwPerHa:NaN},{performanceRatio:1.1},{netIrrigationRatio:-1},{irrigationEfficiency:0},{capexPerKw:-1},{poaKwhPerM2Year:Infinity}])assert.throws(()=>simulateAV('SS01',{...p.SS01,...patch},s));for(const patch of [{areaHa:0},{pumpEfficiency:0},{discountRate:NaN},{lifetimeYears:2.5},{mode:'bad'}])assert.throws(()=>simulateAV('SS01',p.SS01,{...s,...patch}));assert.throws(()=>simulateAV('BAD',p.SS01,s));assert.throws(()=>compareAV(['SS01'],p,s));assert.throws(()=>compareAV(['SS01','SS01'],p,s))})
