import { useState } from 'react'
import { AV_MODELS, type ComparisonSettings, type ModelId, type ModelParameters, type SimulationOutput } from '../lib/avModelLaboratory'
import { DEFAULT_COUPLED, DEFAULT_RESPONSE, syntheticYear, validateDailyData, simulateCoupled, type CoupledSettings, type CoupledParameters, type DailyForcing, type CoupledResult } from '../lib/avCoupledEngine'

const f=(v:number|null|undefined,n=2)=>v===undefined?'Requires daily run':v===null?'N/A':v.toLocaleString('en-US',{maximumFractionDigits:n})
function save(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
type FieldSpec<T>=[keyof T,string,number,number]
const commonFields:FieldSpec<CoupledSettings>[]=[['fieldCapacity','Soil field capacity (m³/m³)',0.01,0.8],['wiltingPoint','Soil wilting point (m³/m³)',0,0.79],['rootDepthM','Root depth (m)',0.01,5],['depletionFraction','Allowable depletion fraction',0.01,0.99],['potentialYieldKgHa','Potential harvest yield (kg/ha per year)',0,1000000],['yieldResponseKy','Crop yield response factor Ky',0,3],['cropMarginPerKg','Net crop contribution (USD/kg; excludes water/energy)',0,1000],['exportPrice','Export electricity price (USD/kWh)',0,100],['waterPriceM3','Water price (USD/m³)',0,1000],['gridKgCo2Kwh','Grid operational emissions (kg CO₂e/kWh)',0,10],['referencePvKwhHa','Standalone PV reference (kWh/ha/year)',0.01,100000000]]
const modelFields:FieldSpec<CoupledParameters>[]=[['etMultiplier','ET multiplier versus open sun',0.01,2],['parTransmission','PAR transmission fraction',0,1],['lightYieldFactor','Independent light yield factor (hypothesis)',0,1.5],['airDeltaC','Air temperature offset (°C)',-15,15],['soilDeltaC','Soil temperature offset (°C)',-15,15],['rhDeltaPct','Relative humidity offset (percentage points)',-30,30],['exportLimitKwhDay','Export limit (kWh/day)',0,1000000000]]
function Fields<T extends object>({spec,values,onChange}:{spec:FieldSpec<T>[];values:T;onChange:(key:keyof T,value:number)=>void}){return <div className="av-fields">{spec.map(([key,label,min,max])=><label className="av-field" key={String(key)}>{label}<input required type="number" step="any" min={min} max={max} value={Number.isNaN(values[key])?'':String(values[key])} onChange={e=>onChange(key,e.target.valueAsNumber)}/></label>)}</div>}
interface Props{results:SimulationOutput[];parameters:Record<ModelId,ModelParameters>;settings:ComparisonSettings}
export function AVSubsystems({results,parameters,settings}:Props){
  const [common,setCommon]=useState({...DEFAULT_COUPLED})
  const [responses,setResponses]=useState(()=>Object.fromEntries(AV_MODELS.map(m=>[m.id,{...DEFAULT_RESPONSE}])) as Record<ModelId,CoupledParameters>)
  const [data,setData]=useState<DailyForcing[]|null>(null),[source,setSource]=useState('No daily data loaded')
  const [coupled,setCoupled]=useState<CoupledResult[]|null>(null),[error,setError]=useState('')
  const reset=()=>{setCoupled(null);setError('')}
  function run(){try{if(!data)throw Error('Load daily data first');setCoupled(results.map(r=>simulateCoupled(r.modelId,parameters[r.modelId],settings,common,responses[r.modelId],data)));setError('')}catch(e){setCoupled(null);setError(e instanceof Error?e.message:'Calculation failed')}}
  const value=(id:ModelId)=>coupled?.find(c=>c.modelId===id)
  const mode=coupled?'Coupled daily scenario':'Annual screening'
  const metric=(label:string,unit:string,get:(r:SimulationOutput,c:CoupledResult|undefined)=>number|null|undefined)=><tr key={label}><th scope="row">{label}<small>{unit}</small></th>{results.map(r=><td key={r.modelId}>{f(get(r,value(r.modelId)))}</td>)}</tr>
  const table=(children:React.ReactNode)=><div className="av-table-scroll" tabIndex={0} role="region" aria-label="Subsystem outcomes"><table><thead><tr><th scope="col">Outcome</th>{results.map(r=><th key={r.modelId} scope="col">{r.modelId}</th>)}</tr></thead><tbody>{children}</tbody></table></div>
  return <section aria-labelledby="av-subsystems"><h2 id="av-subsystems">Six subsystem workspaces</h2><p><strong>{mode}</strong> · Open a subsystem to inspect its outcomes, calculations, and decisions. Annual screening results remain available below; a daily run replaces the values in these six panels.</p>
    <details className="av-coupled-config"><summary>Enable coupled daily simulation — soil, crop, microclimate and resilience</summary>
      <p>Use one complete calendar year. This simplified root-zone bucket and daily energy allocation model is not HYDRUS or an hourly dispatch model. Site data are not fetched automatically. Default crop and soil values are illustrative and must be reviewed.</p>
      <div className="av-toolbar"><button type="button" onClick={()=>{setData(syntheticYear());setSource('Synthetic 2025 example — not observed weather');reset()}}>Load synthetic year</button><button type="button" onClick={()=>save(syntheticYear(),'chipu-daily-template-SYNTHETIC.json')}>Download daily JSON template</button><label className="av-field">Import daily JSON<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;reset();setData(null);setSource('No daily data loaded');try{if(file.size>2000000)throw Error('Use a JSON file below 2 MB');const parsed=validateDailyData(JSON.parse(await file.text()));setData(parsed);setSource(`User-supplied file: ${file.name} — unverified provenance`)}catch(err){setError(err instanceof Error?err.message:'Invalid file')}e.target.value=''}}/></label></div>
      <p role="status">{source}{data?` · ${data.length} days · ${data[0].date} to ${data[data.length-1].date}`:''}</p>
      <details><summary>Daily data fields and interpretation</summary><p>Each row requires date (YYYY-MM-DD), et0Mm, rainMm, poaKwhM2, parMolM2 (daily light integral), airC, soilC, rhPct, kc, criticalLoadKwhHa, waterLimitMm (gross irrigation availability), and gridAvailable (boolean). Set Kc to zero outside the crop season. Daily POA values supply the temporal shape; each model’s entered annual irradiation scales the yearly total. All rainfall infiltrates until field capacity; excess drains. No soil evaporation outside the crop season is modeled.</p></details>
      <form onSubmit={e=>{e.preventDefault();run()}}><details><summary>Shared soil, crop and economic inputs</summary><Fields spec={commonFields} values={common} onChange={(key,v)=>{setCommon(c=>({...c,[key]:v}));reset()}}/></details>
      {results.map(r=><details key={r.modelId}><summary>{r.modelId} · Daily response assumptions</summary><Fields spec={modelFields} values={responses[r.modelId]} onChange={(key,v)=>{setResponses(p=>({...p,[r.modelId]:{...p[r.modelId],[key]:v}}));reset()}}/></details>)}
      <p>PAR transmission, temperature/RH offsets, ET multiplier and light yield factor are independent hypotheses. They are not inferred from panel geometry or automatically calibrated. The annual net-irrigation ratio is not used in daily mode; irrigation follows the soil-water balance.</p>
      <button type="submit" className="av-primary" disabled={!data}>Run coupled daily simulation</button>{error?<p role="alert">{error}</p>:null}</form>
    </details>
    {coupled?<div className="av-toolbar"><strong role="status">Daily simulation complete · {coupled.length} model(s) · {source}</strong><button type="button" onClick={()=>save({schemaVersion:'av-six-subsystems-1.0',generatedAt:new Date().toISOString(),source,evidence:'unvalidated-scenario',common,settings,models:results.map(r=>({id:r.modelId,annual:parameters[r.modelId],response:responses[r.modelId]})),dailyData:data,results:coupled},'chipu-six-subsystem-run.json')}>Export coupled inputs, daily traces &amp; results</button></div>:null}
    <div className="av-subsystem-grid">
    <details className="av-subsystem" open><summary>1. Water &amp; Irrigation</summary>{table(<>
      {metric('Applied irrigation','m³/year',(r,c)=>c?c.av.irrigation:r.irrigationM3)}
      {metric('Irrigation intensity','m³/ha/year',(r,c)=>c?c.av.irrigation/c.areaHa:r.irrigationM3PerHa)}
      {metric('Water saved vs open sun','%',(r,c)=>c?c.waterSavedPct:r.waterSavedPct)}
      {metric('Crop evapotranspiration','mm/year',(_,c)=>c?.av.et)}
      {metric('Irrigation water productivity','kg/m³',(_,c)=>c?.waterProductivity)}
    </>)}<details><summary>How calculated</summary><p>Annual applied water = net depth × 10 × hectares × irrigation ratio ÷ efficiency. Daily mode instead refills the root-zone deficit when it reaches the depletion threshold, subject to water and pumping-energy availability. Savings use the same-area open-sun run. Water productivity = harvest mass ÷ applied irrigation; it excludes rainfall.</p></details><p><strong>Decisions:</strong> compare application efficiency, adjust depletion threshold, test water limits, reduce pumping head, and compare irrigation productivity. Lower applied water alone can reflect shortage rather than improvement; inspect crop stress too.</p></details>
    <details className="av-subsystem"><summary>2. Energy</summary>{table(<>
      {metric('PV generation','kWh/year',(r,c)=>c?c.av.pv:r.pvEnergyKwh)}
      {metric('Pump electricity','kWh/year',(r,c)=>c?c.av.pump:r.pumpEnergyKwh)}
      {metric('PV consumed on site','kWh/year',(_,c)=>c?.av.self)}
      {metric('Grid imports','kWh/year',(_,c)=>c?.av.imports)}
      {metric('Export / curtailment combined','kWh/year',(_,c)=>c?c.av.exports+c.av.curtailed:undefined)}
      {metric('Electricity exported','kWh/year',(_,c)=>c?.av.exports)}{metric('Electricity curtailed','kWh/year',(_,c)=>c?.av.curtailed)}
    </>)}<details><summary>How calculated</summary><p>PV = kW × annual POA irradiation × performance ratio / 1 kW/m². Pump kWh = m³ × 1,000 × 9.81 × head / (3,600,000 × efficiency). Daily allocation prioritizes irrigation, then critical load, then permitted export; surplus is curtailed. Daily matching assumes within-day flexibility and overestimates hourly self-consumption. No battery, night operation or islanding hardware is modeled.</p></details><p><strong>Decisions:</strong> compare PV density, pump efficiency, load size, export limits, and outage scenarios. Battery sizing requires an hourly model.</p></details>
    <details className="av-subsystem"><summary>3. Crop &amp; Yield</summary>{table(<>
      {metric('Harvest yield estimate','kg/ha/year',(_,c)=>c?.av.yieldKgHa)}
      {metric('Yield change vs open sun','%',(_,c)=>c?.yieldChangePct)}
      {metric('Water-stress exposure','growing days',(_,c)=>c?.av.stressDays)}
      {metric('Mean water-stress coefficient','0–1; 1 = unstressed',(_,c)=>c?.av.meanKs)}
      {metric('Light-response multiplier','input hypothesis',(r,c)=>c?responses[r.modelId].lightYieldFactor:undefined)}
    </>)}<details><summary>How calculated</summary><p>Yield = potential yield × max(0, 1 − Ky × (1 − actual ET / potential ET)) × the independent light-response factor. This is an exploratory combination of a seasonal water-response relationship and a user-entered light factor. It does not predict crop response from PAR or temperature. Biomass and phenology are not modeled.</p><a href="https://www.fao.org/4/X0490E/x0490e0e.htm" target="_blank" rel="noreferrer">FAO soil-water stress and yield-response background</a></details><p><strong>Decisions:</strong> test crop parameters, growing season through Kc, irrigation thresholds, assumed light tolerance, and yield–water trade-offs. Use crop-specific evidence before interpreting estimates as predictions.</p></details>
    <details className="av-subsystem"><summary>4. Techno-economics</summary>{table(<>
      {metric('Initial capital investment','USD',(r)=>r.capitalCost)}
      {metric('Annual operating cost','USD/year',(r)=>r.annualOperatingCost)}
      {metric('Annual incremental net cash flow','USD/year',(r,c)=>c?c.cashFlow:r.annualCashFlow)}
      {metric('Simple payback','years; N/A if cash flow ≤ 0',(r,c)=>c?c.payback:r.simplePaybackYears)}
      {metric('Net present value','USD',(r,c)=>c?c.npv:r.npv)}
      {metric('Annualized net benefit','USD/year',(r,c)=>c?c.annualizedBenefit:r.annualizedNetBenefit)}
    </>)}{results.map(r=>{const c=value(r.modelId),p=parameters[r.modelId],cash=c?c.cashFlow:r.annualCashFlow,payback=c?c.payback:r.simplePaybackYears;const factor=settings.discountRate===0?settings.lifetimeYears:(1-(1+settings.discountRate)**(-settings.lifetimeYears))/settings.discountRate;return <details key={r.modelId}><summary>{r.modelId} · Show payback calculation</summary><dl className="av-calculation"><dt>Initial investment</dt><dd>{f(r.capacityKw)} kW × ${f(p.capexPerKw)}/kW = <strong>${f(r.capitalCost)}</strong></dd>{c?<><dt>Avoided grid cost</dt><dd>({f(c.baseline.imports)} − {f(c.av.imports)}) kWh × ${f(settings.electricityValuePerKwh)}/kWh = ${f(c.gridSavings)}</dd><dt>Export revenue</dt><dd>{f(c.av.exports)} kWh × ${f(common.exportPrice)}/kWh = ${f(c.exportRevenue)}</dd><dt>Crop margin change</dt><dd>({f(c.av.yieldKgHa)} − {f(c.baseline.yieldKgHa)}) kg/ha × {f(c.areaHa)} ha × ${f(common.cropMarginPerKg)}/kg = ${f(c.cropMargin)}</dd><dt>Water-cost savings</dt><dd>({f(c.baseline.irrigation)} − {f(c.av.irrigation)}) m³ × ${f(common.waterPriceM3)}/m³ = ${f(c.waterSavings)}</dd></>:<><dt>PV electricity value</dt><dd>{f(r.pvEnergyKwh)} kWh × ${f(settings.electricityValuePerKwh)}/kWh = ${f(r.pvEnergyKwh*settings.electricityValuePerKwh)}</dd><dt>Avoided pump electricity cost</dt><dd>({f(r.baselinePumpEnergyKwh)} − {f(r.pumpEnergyKwh)}) kWh × ${f(settings.electricityValuePerKwh)}/kWh = ${f((r.baselinePumpEnergyKwh-r.pumpEnergyKwh)*settings.electricityValuePerKwh)}</dd></>}<dt>Annual operating cost</dt><dd>{f(r.capacityKw)} kW × ${f(p.opexPerKwYear)}/kW/year = ${f(r.annualOperatingCost)}</dd><dt>Annual incremental net cash flow</dt><dd>Benefits above − operating cost = <strong>${f(cash)}/year</strong></dd><dt>Simple payback</dt><dd>{payback===null?'No finite payback: net cash flow is not positive.':`$${f(r.capitalCost)} ÷ $${f(cash)}/year = ${f(payback)} years`}{payback!==null&&payback>settings.lifetimeYears?' — exceeds the project life.':''}</dd><dt>Discounting</dt><dd>Rate {f(settings.discountRate*100)}%; life {settings.lifetimeYears} years; annuity factor {f(factor,4)}</dd><dt>NPV</dt><dd>−${f(r.capitalCost)} + ${f(cash)} × {f(factor,4)} = ${f(c?c.npv:r.npv)}</dd><dt>Annualized benefit</dt><dd>${f(cash)} − ${f(r.capitalCost)} / {f(factor,4)} = ${f(c?c.annualizedBenefit:r.annualizedNetBenefit)}/year. This is not the payback denominator.</dd></dl><CashFlow capital={r.capitalCost} cash={cash} years={settings.lifetimeYears}/></details>})}<p><strong>Decisions:</strong> set an investment ceiling, compare net cash flow, inspect break-even timing, test tariffs and crop margins, and compare discounted value. Fixed yearly cash flow; no degradation, replacements, tax or financing. Costs must include the infrastructure assumed in daily operation.</p></details>
    <details className="av-subsystem"><summary>5. Microclimate &amp; Soil</summary>{table(<>
      {metric('Crop-level daily light integral','mol/m²/day; growing season',(_,c)=>c?.av.meanDli)}
      {metric('Mean air temperature','°C; whole year',(_,c)=>c?.av.meanAirC)}
      {metric('Mean vapour-pressure deficit','kPa; whole year',(_,c)=>c?.av.meanVpd)}
      {metric('Mean soil temperature','°C; whole year',(_,c)=>c?.av.meanSoilC)}
      {metric('Mean root-zone water content','m³/m³; whole year',(_,c)=>c?.av.meanTheta)}
    </>)}<details><summary>How calculated</summary><p>TAW = 1,000 × (field capacity − wilting point) × root depth. Initial root zone is at field capacity. Daily balance adds rainfall and efficient irrigation, removes actual ET and drainage. PAR = supplied daily light × transmission. Temperatures and RH use user-entered offsets (RH is bounded to 0–100%). VPD = 0.6108 × exp(17.27 T / (T + 237.3)) × (1 − RH/100). No thermal or geometric shading solver is present.</p></details><p><strong>Decisions:</strong> compare transmission hypotheses, inspect humidity conditions, test root depth, choose irrigation trigger thresholds, and identify which soil and microclimate measurements are needed.</p></details>
    <details className="av-subsystem"><summary>6. Resilience &amp; Environmental Performance</summary>{table(<>
      {metric('Irrigation volume delivered / requested','%',(_,c)=>c?.av.irrigationReliability)}
      {metric('Unserved critical electricity','kWh/year',(_,c)=>c?.av.unserved)}
      {metric('Longest unmet-irrigation sequence','days',(_,c)=>c?.av.longestDeficit)}
      {metric('Avoided operational grid emissions','kg CO₂e/year',(_,c)=>c?.avoidedOperationalKgCo2)}
      {metric('Land-equivalent ratio','crop ratio + PV ratio',(_,c)=>c?.ler)}
    </>)}<details><summary>How calculated</summary><p>Reliability = delivered / requested irrigation volume; no requests gives N/A. Shortage duration counts consecutive days with unmet irrigation requests. Avoided emissions = (baseline − model grid imports) × the supplied grid factor; exported electricity receives no emissions credit. This excludes embodied emissions. LER = AV yield / open-sun yield + AV PV per hectare / standalone-PV reference. Both reference systems must be locally comparable.</p></details><p><strong>Decisions:</strong> test water restrictions, grid outages, critical-load levels, export constraints, and land-use trade-offs. Daily supply is an ideal allocation scenario, not a guarantee of outage operation or resilience.</p></details>
    </div>
  </section>
}
function CashFlow({capital,cash,years}:{capital:number;cash:number;years:number}){const min=Math.min(-capital,-capital+cash*years),max=Math.max(0,-capital,-capital+cash*years),span=Math.max(1,max-min);const y=(v:number)=>135-(v-min)/span*115;return <figure className="av-cash-chart"><figcaption>Cumulative undiscounted cash flow · USD · constant annual cash flow</figcaption><svg viewBox="0 0 420 170" role="img" aria-label={`Cumulative cash flow from minus ${capital} dollars at year zero to ${-capital+cash*years} dollars at year ${years}`}><line x1="55" y1={y(0)} x2="395" y2={y(0)} stroke="#a18d52" strokeDasharray="4 3"/><polyline points={`55,${y(-capital)} 395,${y(-capital+cash*years)}`} fill="none" stroke="#006b3c" strokeWidth="3"/><text x="55" y="160" fontSize="11">Year 0</text><text x="355" y="160" fontSize="11">Year {years}</text><text x="55" y="13" fontSize="11">Start: ${f(-capital)} · End: ${f(-capital+cash*years)}</text><text x="8" y={y(0)+4} fontSize="11">$0</text></svg></figure>}
