import { useEffect,useState } from 'react'
import { BatteryCharging, Play, SunMedium, Zap } from 'lucide-react'
import { runEnergyAnalysis,type EnergyAnalysisResult } from '../lib/energy-intelligence-engine'
import { listTwinStates,type TwinStateEstimate } from '../lib/state-engine'
import { ResearchWorkspaceGrammar } from './ResearchWorkspaceGrammar'

export function EnergyIntelligenceWorkspace(){
 const [states,setStates]=useState<TwinStateEstimate[]>([]); const [stateId,setStateId]=useState(''); const [result,setResult]=useState<EnergyAnalysisResult|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{listTwinStates(30).then(s=>{setStates(s);if(s[0])setStateId(s[0].id)}).catch(e=>setError(String(e)))},[])
 async function run(){if(!stateId){setError('Create a Twin State first.');return}setBusy(true);setError('');try{setResult(await runEnergyAnalysis({stateId}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="energy-engine-workspace">
  <section className="energy-engine-hero"><div><span>WATER–ENERGY DIGITAL TWIN · RESEARCH DEMONSTRATION</span><h1>Energy Intelligence</h1><p>Connect predicted electricity availability, irrigation pumping demand, battery reserve, and agricultural loads in one traceable energy balance.</p></div><div className="energy-engine-actions"><select value={stateId} onChange={e=>setStateId(e.target.value)}><option value="">Select Twin State</option>{states.map(s=><option key={s.id} value={s.id}>{s.id} · {s.evidenceMode}</option>)}</select><button onClick={run} disabled={busy}><Play size={15}/>{busy?'Analyzing…':'Run Energy Analysis'}</button></div></section>
  <ResearchWorkspaceGrammar active={['Context','Inputs','Method / Model','State / Indicators','FEW Dependencies','Outputs','Uncertainty','Provenance']} note="Energy analysis consumes Twin State, matching prediction when available, and Water Intelligence pumping demand. Demonstration parameters remain identified as assumptions." />
  {error&&<div className="energy-engine-warning">{error}</div>}
  {result&&<><section className="energy-engine-meta"><div><small>ANALYSIS</small><strong>{result.id}</strong></div><div><small>STATE</small><strong>{result.stateId}</strong></div><div><small>FORECAST</small><strong>{result.forecastId??'NONE'}</strong></div><div><small>WATER LINK</small><strong>{result.waterAnalysisId}</strong></div><div><small>EVIDENCE</small><strong>{result.evidenceMode}</strong></div><div><small>STATUS</small><strong>{result.status}</strong></div></section>
  {result.warnings.map(w=><div className="energy-engine-warning" key={w}>{w}</div>)}
  <section className="energy-engine-kpis"><article><SunMedium/><span>Predicted PV energy</span><strong>{result.predictedPvEnergyKwh.toFixed(1)} kWh</strong><small>{result.horizonHours} h horizon</small></article><article><BatteryCharging/><span>Usable battery energy</span><strong>{result.usableBatteryEnergyKwh.toFixed(1)} kWh</strong><small>{result.reserveFloorPct}% reserve protected</small></article><article><Zap/><span>Total agricultural demand</span><strong>{result.totalDemandKwh.toFixed(1)} kWh</strong><small>{result.pumpingDemandKwh.toFixed(1)} kWh pumping</small></article><article><Zap/><span>Unmet demand</span><strong>{result.unmetEnergyKwh.toFixed(1)} kWh</strong><small>{result.surplusEnergyKwh.toFixed(1)} kWh surplus</small></article></section>
  <section className="energy-flow-card"><h2>Water–energy coupling</h2><div className="energy-flow-line"><div><b>Water Intelligence</b><span>{result.pumpingDemandKwh.toFixed(2)} kWh pumping demand</span></div><i>→</i><div><b>Available electricity</b><span>{result.totalAvailableEnergyKwh.toFixed(2)} kWh</span></div><i>→</i><div><b>Priority allocation</b><span>{result.servedEnergyKwh.toFixed(2)} kWh served</span></div></div>{result.waterEnergyIntensityKwhM3!==null&&<p>Modeled water–energy intensity: <strong>{result.waterEnergyIntensityKwhM3} kWh/m³</strong>.</p>}</section>
  <section className="energy-allocation-card"><h2>Agricultural load allocation</h2><table><thead><tr><th>Priority</th><th>Load</th><th>Demand</th><th>Served</th><th>Unmet</th><th>Service</th></tr></thead><tbody>{result.allocations.map(a=><tr key={a.load}><td>{a.priority}</td><td>{a.load.replace('_',' ')}</td><td>{a.demandKwh.toFixed(2)} kWh</td><td>{a.servedKwh.toFixed(2)} kWh</td><td>{a.unmetKwh.toFixed(2)} kWh</td><td>{a.demandKwh===0?'—':Math.round(a.servedKwh/a.demandKwh*100)+'%'}</td></tr>)}</tbody></table></section>
  <section className="energy-method-card"><h2>Method & limitations</h2><p>{result.method}</p><p>Model version: <strong>{result.modelVersion}</strong>. Battery capacity and non-pumping loads are demonstration parameters until replaced by documented system configuration or measured values.</p></section></>}
  {!result&&<section className="energy-engine-empty"><h2>Ready for integrated energy analysis</h2><p>Select a persisted Twin State. The engine will use its matching prediction when available and call Water Intelligence to derive the pumping-energy requirement.</p></section>}
 </div>
}
