import { Link } from 'react-router-dom'
import { ChevronDown, MapPin } from 'lucide-react'
import { farmState, scenarios } from '../lib/cropsmart-model'
import { useResearchContext } from '../lib/research-context'
export function ResearchContextBar(){
 const {profiles,profile,selectProfile,zoneId,setZoneId,scenario,setScenario}=useResearchContext()
 const names=new Intl.DisplayNames(['en'],{type:'region'})
 return <header className="research-context-bar"><div className="research-mode"><MapPin size={14}/><span>{profile.kind==='demonstrator'?'Demonstrator':'Place-based research'}</span></div><div className="research-context-summary"><strong>{profile.country?names.of(profile.country):'Location unverified'}</strong><span>→</span><strong>{profile.region||'Region unverified'}</strong><span>→</span><strong>{profile.name}</strong><span>→</span><strong>{zoneId}</strong><span>→</span><strong>{profile.experiment||'No experiment selected'}</strong><span>→</span><strong>{scenario}</strong></div><details className="context-editor"><summary>Change context <ChevronDown size={13}/></summary><div className="context-editor-panel"><label>Research site<select value={profile.id} onChange={e=>selectProfile(e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{profile.kind==='demonstrator'?<label>Zone<select value={zoneId} onChange={e=>setZoneId(e.target.value)}>{farmState.zones.map(z=><option key={z.id}>{z.id}</option>)}</select></label>:<p>{profile.systemType} · {profile.zone}</p>}<label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select></label><Link to="/app/location">Add or edit location & system</Link><small>Location configuration does not establish model validation.</small></div></details></header>
}
