import { useEffect,useState } from 'react'
import { Play, Scale } from 'lucide-react'
import { runResourceAllocation,type ResourceAllocationResult } from '../lib/resource-allocation-engine'
import { listTwinStates,type TwinStateEstimate } from '../lib/state-engine'

export function ResourceAllocationWorkspace(){
 const [states,setStates]=useState<TwinStateEstimate[]>([]); const [stateId,setStateId]=useState(''); const [result,setResult]=useState<ResourceAllocationResult|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{listTwinStates(30).then(s=>{setStates(s);if(s[0])setStateId(s[0].id)}).catch(e=>setError(String(e)))},[])
 async function run(){if(!stateId){setError('Create a Twin State first.');return}setBusy(true);setError('');try{setResult(await runResourceAllocation({stateId}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="resource-allocation-workspace">
  <section className="resource-allocation-hero"><div><span>AGRICULTURAL-CONSEQUENCE-AWARE DECISION ANALYSIS</span><h1>Resource Allocation</h1><p>Compare alternative water–energy allocation strategies by their modeled agricultural consequences rather than by energy balance alone.</p></div><div className="resource-allocation-actions"><select value={stateId} onChange={e=>setStateId(e.target.value)}><option value="">Select Twin State</option>{states.map(s=><option key={s.id} value={s.id}>{s.id} · {s.evidenceMode}</option>)}</select><button onClick={run} disabled={busy}><Play size={15}/>{busy?'Evaluating…':'Compare Strategies'}</button></div></section>
  {error&&<div className="resource-allocation-warning">{error}</div>}
  {result&&<><section className="resource-allocation-meta"><div><small>ANALYSIS</small><strong>{result.id}</strong></div><div><small>STATE</small><strong>{result.stateId}</strong></div><div><small>WATER LINK</small><strong>{result.waterAnalysisId}</strong></div><div><small>ENERGY LINK</small><strong>{result.energyAnalysisId}</strong></div><div><small>EVIDENCE</small><strong>{result.evidenceMode}</strong></div><div><small>STATUS</small><strong>{result.status}</strong></div></section>
  {result.warnings.map(w=><div className="resource-allocation-warning" key={w}>{w}</div>)}
  <section className="resource-allocation-recommendation"><Scale/><div><small>LOWEST MODELED CONSEQUENCE</small><h2>{result.recommendedStrategy.replaceAll('_',' ')}</h2><p>This is the lowest-scoring research strategy under the current explicit weights. It is not an autonomous control command.</p></div></section>
  <section className="resource-weights"><h2>Consequence weights</h2><div>{Object.entries(result.weights).map(([k,v])=><article key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{v.toFixed(2)}</strong></article>)}</div></section>
  <section className="strategy-grid">{result.evaluations.map(e=><article key={e.strategy} className={e.status==='BEST'?'best-strategy':''}><header><div><span>{e.status}</span><h3>{e.strategy.replaceAll('_',' ')}</h3></div><strong>{e.consequenceScore.toFixed(3)}</strong></header><p>{e.explanation}</p><dl><div><dt>Irrigation served</dt><dd>{Math.round(e.irrigationFraction*100)}%</dd></div><div><dt>Pumping</dt><dd>{e.pumpingEnergyAllocatedKwh.toFixed(1)} kWh</dd></div><div><dt>Cooling</dt><dd>{e.coolingEnergyAllocatedKwh.toFixed(1)} kWh</dd></div><div><dt>Critical</dt><dd>{e.criticalEnergyAllocatedKwh.toFixed(1)} kWh</dd></div><div><dt>Reserve retained</dt><dd>{e.reserveEnergyRetainedKwh.toFixed(1)} kWh</dd></div></dl></article>)}</section>
  <section className="consequence-table"><h2>Modeled consequence indices</h2><table><thead><tr><th>Strategy</th><th>Water deficit</th><th>Energy deficit</th><th>Crop risk</th><th>Food-loss risk</th><th>Critical-load gap</th><th>Operating-cost index</th><th>Score ↓</th></tr></thead><tbody>{result.evaluations.map(e=><tr key={e.strategy}><td>{e.strategy.replaceAll('_',' ')}</td><td>{e.expectedWaterDeficitIndex.toFixed(3)}</td><td>{e.expectedEnergyDeficitIndex.toFixed(3)}</td><td>{e.expectedCropRiskIndex.toFixed(3)}</td><td>{e.expectedFoodLossRiskIndex.toFixed(3)}</td><td>{e.unmetCriticalLoadIndex.toFixed(3)}</td><td>{e.operatingCostIndex.toFixed(3)}</td><td><strong>{e.consequenceScore.toFixed(3)}</strong></td></tr>)}</tbody></table></section>
  <section className="resource-allocation-method"><h2>Method & limitations</h2><p>{result.method}</p><p>Model version: <strong>{result.modelVersion}</strong>. The present consequence functions are transparent demonstration logic intended to support research development, sensitivity analysis, and later calibration.</p></section></>}
  {!result&&<section className="resource-allocation-empty"><h2>Ready for strategy comparison</h2><p>Select a Twin State and run the comparison. CropSmart will call the Water and Energy Intelligence layers, evaluate four management strategies, and rank them by explicit consequence criteria.</p></section>}
 </div>
}
