import { useEffect,useState } from 'react'
import { BarChart3, Download, Play, ShieldCheck } from 'lucide-react'
import { exportEnsembleRun,listEnsembleRuns,runUncertaintyEnsemble,type EnsembleRun } from '../lib/uncertainty-ensemble-engine'
import { listTwinStates,type TwinStateEstimate } from '../lib/state-engine'
import { scenarioCatalog } from '../lib/scenario-laboratory-engine'

function label(v:string){return v.replace(/_/g,' ')}
function downloadJson(run:EnsembleRun){const blob=new Blob([exportEnsembleRun(run)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${run.id}.json`;a.click();URL.revokeObjectURL(url)}

export function UncertaintyExplorerWorkspace(){
 const [states,setStates]=useState<TwinStateEstimate[]>([]),[stateId,setStateId]=useState(''),[scenarioId,setScenarioId]=useState('S00'),[sampleCount,setSampleCount]=useState(300),[seed,setSeed]=useState(20260904),[result,setResult]=useState<EnsembleRun|null>(null),[history,setHistory]=useState<EnsembleRun[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{Promise.all([listTwinStates(30),listEnsembleRuns(20)]).then(([s,h])=>{setStates(s);setHistory(h);if(s[0])setStateId(s[0].id)}).catch(e=>setError(String(e)))},[])
 async function run(){if(!stateId){setError('Create a Twin State first.');return}setBusy(true);setError('');try{const r=await runUncertaintyEnsemble({stateId,scenarioId,sampleCount,seed});setResult(r);setHistory(await listEnsembleRuns(20))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="uncertainty-workspace">
  <section className="uncertainty-hero"><div><span>ENSEMBLE UNCERTAINTY ANALYSIS · RESEARCH DEMONSTRATION</span><h1>Uncertainty Explorer</h1><p>Test whether management-strategy rankings remain stable when key water, energy, storage, and load assumptions vary across a reproducible seeded ensemble.</p></div><div className="uncertainty-controls"><select value={stateId} onChange={e=>setStateId(e.target.value)}><option value="">Select Twin State</option>{states.map(s=><option key={s.id} value={s.id}>{s.id} · {s.evidenceMode}</option>)}</select><select value={scenarioId} onChange={e=>setScenarioId(e.target.value)}>{scenarioCatalog.map(s=><option key={s.id} value={s.id}>{s.id} · {s.name}</option>)}</select><input type="number" min={50} max={2000} step={50} value={sampleCount} onChange={e=>setSampleCount(Number(e.target.value)||300)} aria-label="Sample count"/><input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value)||20260904)} aria-label="Random seed"/><button onClick={run} disabled={busy}><Play size={15}/>{busy?'Running…':'Run Ensemble'}</button></div></section>
  {error&&<div className="uncertainty-warning">{error}</div>}
  {result&&<><section className="uncertainty-meta"><div><small>RUN</small><strong>{result.id}</strong></div><div><small>STATE</small><strong>{result.stateId}</strong></div><div><small>SCENARIO</small><strong>{result.scenarioId}</strong></div><div><small>SAMPLES</small><strong>{result.sampleCount}</strong></div><div><small>SEED</small><strong>{result.seed}</strong></div><div><small>EVIDENCE</small><strong>{result.evidenceMode}</strong></div></section>
  {result.warnings.map(w=><div className="uncertainty-warning" key={w}>{w}</div>)}
  <section className="robust-card"><ShieldCheck/><div><small>MOST ROBUST UNDER THIS ENSEMBLE</small><h2>{label(result.robustStrategy)}</h2><p>Lowest modeled consequence in <strong>{Math.round(result.robustStrategyProbability*100)}%</strong> of ensemble members.</p></div><button onClick={()=>downloadJson(result)}><Download size={15}/> Export JSON</button></section>
  <section className="uncertainty-grid">{result.strategyDistributions.map(d=><article key={d.strategy}><header><span>{label(d.strategy)}</span><strong>{Math.round(d.bestProbability*100)}%</strong></header><div className="interval"><b>{d.medianScore.toFixed(3)}</b><small>median score</small></div><div className="interval-range"><span>P10 {d.p10.toFixed(3)}</span><i></i><span>P90 {d.p90.toFixed(3)}</span></div><dl><div><dt>Mean</dt><dd>{d.meanScore.toFixed(3)}</dd></div><div><dt>Water deficit</dt><dd>{d.meanWaterDeficitIndex.toFixed(3)}</dd></div><div><dt>Energy deficit</dt><dd>{d.meanEnergyDeficitIndex.toFixed(3)}</dd></div><div><dt>Crop risk</dt><dd>{d.meanCropRiskIndex.toFixed(3)}</dd></div><div><dt>Food-loss risk</dt><dd>{d.meanFoodLossRiskIndex.toFixed(3)}</dd></div></dl></article>)}</section>
  <section className="sensitivity-card"><div className="section-title"><BarChart3/><div><h2>Sensitivity ranking</h2><p>Correlation between uncertain inputs and the robust-strategy consequence score.</p></div></div><table><thead><tr><th>Rank</th><th>Parameter</th><th>Correlation</th><th>|r|</th></tr></thead><tbody>{result.sensitivity.map((s,i)=><tr key={s.parameter}><td>{i+1}</td><td>{s.label}</td><td>{s.correlation.toFixed(3)}</td><td><strong>{s.absoluteCorrelation.toFixed(3)}</strong></td></tr>)}</tbody></table></section>
  <section className="uncertainty-method"><h2>Method & limitations</h2><p>{result.method}</p><p>Model version: <strong>{result.modelVersion}</strong>. Parameter version: <strong>{result.parameterVersion}</strong>. P10/P90 values are ensemble quantiles, not validated confidence intervals.</p></section></>}
  {!result&&<section className="uncertainty-empty"><h2>Ready for uncertainty analysis</h2><p>Select a Twin State and scenario, then run a seeded ensemble. CropSmart will perturb transparent research parameters, recalculate strategy consequences, and report robustness and sensitivity.</p></section>}
  {history.length>0&&<section className="uncertainty-history"><h2>Ensemble history</h2><table><thead><tr><th>Run</th><th>Scenario</th><th>Samples</th><th>Robust strategy</th><th>Probability</th><th>Created</th></tr></thead><tbody>{history.map(h=><tr key={h.id} onClick={()=>setResult(h)}><td>{h.id}</td><td>{h.scenarioId}</td><td>{h.sampleCount}</td><td>{label(h.robustStrategy)}</td><td>{Math.round(h.robustStrategyProbability*100)}%</td><td>{new Date(h.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section>}
 </div>
}
