import { Navigate, Route, Routes } from 'react-router-dom'
import { AppLayout } from './layouts/AppLayout'
import { CropSmartWorkspace } from './components/CropSmartWorkspace'
import { DataProvenanceWorkspace } from './components/DataProvenanceWorkspace'
import { TwinStateWorkspace } from './components/TwinStateWorkspace'
import { ForecastWorkspace } from './components/ForecastWorkspace'
import { WaterIntelligenceWorkspace } from './components/WaterIntelligenceWorkspace'
import { EnergyIntelligenceWorkspace } from './components/EnergyIntelligenceWorkspace'
import { ResourceAllocationWorkspace } from './components/ResourceAllocationWorkspace'
import { ScenarioLaboratoryWorkspace } from './components/ScenarioLaboratoryWorkspace'
import { UncertaintyExplorerWorkspace } from './components/UncertaintyExplorerWorkspace'
import { ExperimentRegistryWorkspace } from './components/ExperimentRegistryWorkspace'
import { ResearchExportWorkspace } from './components/ResearchExportWorkspace'
import { ModelsMethodsWorkspace } from './components/ModelsMethodsWorkspace'
import { ModelCalibrationValidationWorkspace } from './components/ModelCalibrationValidationWorkspace'
import { ToastBridge } from './components/ToastBridge'
const screens=[['farm','twin'],['agrivoltaics','comparison'],['crops','crop'],['storage','storage'],['about','about']] as const
export default function App(){return <><ToastBridge/><Routes><Route element={<AppLayout/>}><Route path="/" element={<Navigate to="/app" replace/>}/><Route path="/app" element={<CropSmartWorkspace screen="home"/>}/><Route path="/app/data" element={<DataProvenanceWorkspace/>}/><Route path="/app/twin-state" element={<TwinStateWorkspace/>}/><Route path="/app/state" element={<TwinStateWorkspace/>}/><Route path="/app/forecast" element={<ForecastWorkspace/>}/><Route path="/app/water" element={<WaterIntelligenceWorkspace/>}/><Route path="/app/energy" element={<EnergyIntelligenceWorkspace/>}/><Route path="/app/resource-allocation" element={<ResourceAllocationWorkspace/>}/><Route path="/app/resources" element={<ResourceAllocationWorkspace/>}/><Route path="/app/scenarios" element={<ScenarioLaboratoryWorkspace/>}/><Route path="/app/scenario-laboratory" element={<ScenarioLaboratoryWorkspace/>}/><Route path="/app/uncertainty" element={<UncertaintyExplorerWorkspace/>}/><Route path="/app/uncertainty-explorer" element={<UncertaintyExplorerWorkspace/>}/><Route path="/app/experiments" element={<ExperimentRegistryWorkspace/>}/><Route path="/app/experiment-registry" element={<ExperimentRegistryWorkspace/>}/><Route path="/app/export" element={<ResearchExportWorkspace/>}/><Route path="/app/research-export" element={<ResearchExportWorkspace/>}/><Route path="/app/methods" element={<ModelsMethodsWorkspace/>}/><Route path="/app/models-methods" element={<ModelsMethodsWorkspace/>}/><Route path="/app/calibration-validation" element={<ModelCalibrationValidationWorkspace/>}/><Route path="/app/model-validation" element={<ModelCalibrationValidationWorkspace/>}/>{screens.map(([path,screen])=><Route key={path} path={`/app/${path}`} element={<CropSmartWorkspace screen={screen}/>}/>)}<Route path="/app/twin" element={<CropSmartWorkspace screen="twin"/>}/><Route path="/app/comparison" element={<CropSmartWorkspace screen="comparison"/>}/><Route path="/app/crop" element={<CropSmartWorkspace screen="crop"/>}/><Route path="/app/*" element={<Navigate to="/app" replace/>}/></Route></Routes></>}
