import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './index.css'
import './professional-ui.css'
import './interface-polish.css'
import './data-engine.css'
import './twin-state.css'
import './forecast-engine.css'
import './water-engine.css'
import './energy-engine.css'
import './resource-allocation.css'
import './scenario-lab.css'
import './uncertainty-explorer.css'
import './experiment-registry.css'
import './research-export.css'
import './models-methods.css'
import './model-calibration-validation.css'
import './field-sensor-integration.css'
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>)
