create extension if not exists pgcrypto;
create table if not exists public.cs_devices(id text primary key,label text not null,transport text not null check(transport in('HTTP','MQTT','LORA_BRIDGE','DATA_LOGGER','MANUAL_GATEWAY')),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.cs_device_keys(id uuid primary key default gen_random_uuid(),device_id text not null references public.cs_devices(id) on delete cascade,key_hash text not null unique,revoked boolean not null default false,created_at timestamptz not null default now(),last_used_at timestamptz);
create table if not exists public.cs_sensors(id text primary key,farm_id text not null,zone_id text not null,variable text not null,unit text not null,expected_interval_minutes integer not null check(expected_interval_minutes>0),active boolean not null default true,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.cs_ingestion_messages(id uuid primary key default gen_random_uuid(),device_id text not null references public.cs_devices(id),message_id text not null unique,sent_at timestamptz not null,received_at timestamptz not null default now(),transport text not null,status text not null,point_count integer not null,accepted_count integer not null default 0,rejected_count integer not null default 0,clock_drift_seconds numeric,messages jsonb not null default '[]'::jsonb);
create table if not exists public.cs_observations(id uuid primary key default gen_random_uuid(),farm_id text not null,zone_id text not null,sensor_id text not null references public.cs_sensors(id),variable text not null,value double precision not null,unit text not null,observed_at timestamptz not null,provenance text not null default 'MEASURED',quality text not null default 'PASS',source_name text not null,source_dataset text,uncertainty double precision,note text,ingestion_id uuid references public.cs_ingestion_messages(id),created_at timestamptz not null default now(),unique(sensor_id,variable,observed_at,source_dataset));
create index if not exists cs_obs_time_idx on public.cs_observations(observed_at desc);create index if not exists cs_obs_sensor_idx on public.cs_observations(sensor_id,observed_at desc);create index if not exists cs_obs_zone_idx on public.cs_observations(farm_id,zone_id,observed_at desc);
create table if not exists public.cs_device_heartbeats(device_id text primary key references public.cs_devices(id) on delete cascade,last_seen_at timestamptz not null,last_sent_at timestamptz not null,transport text not null,clock_drift_seconds numeric not null default 0,updated_at timestamptz not null default now());
create table if not exists public.cs_quarantine(id uuid primary key default gen_random_uuid(),received_at timestamptz not null default now(),device_id text,message_id text,reason text not null,payload jsonb not null,resolved boolean not null default false,resolution_note text);
create table if not exists public.cs_experiments(id text primary key,title text not null,state_id text,evidence_mode text,model_versions jsonb not null default '{}'::jsonb,parameter_versions jsonb not null default '{}'::jsonb,lineage jsonb not null default '[]'::jsonb,reproducibility_key text not null,manifest jsonb not null,created_at timestamptz not null default now());
create table if not exists public.cs_audit_log(id uuid primary key default gen_random_uuid(),occurred_at timestamptz not null default now(),actor_type text not null,actor_id text,action text not null,entity_type text not null,entity_id text,details jsonb not null default '{}'::jsonb);
create index if not exists cs_audit_time_idx on public.cs_audit_log(occurred_at desc);
alter table public.cs_devices enable row level security;alter table public.cs_device_keys enable row level security;alter table public.cs_sensors enable row level security;alter table public.cs_ingestion_messages enable row level security;alter table public.cs_observations enable row level security;alter table public.cs_device_heartbeats enable row level security;alter table public.cs_quarantine enable row level security;alter table public.cs_experiments enable row level security;alter table public.cs_audit_log enable row level security;
-- No anonymous policies are created. Server functions use the service-role credential; browser clients cannot directly write research records.
